---

- name: Add Google Chrome repository apt key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Check if Google Chrome apt repository exists
  stat:
    path: /etc/apt/sources.list.d/google-chrome.list
  register: gchrome_stat_result

- name: Configure Google Chrome apt repository
  apt_repository:
    filename: google-chrome
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
  when: not gchrome_stat_result.stat.exists

- name: Install Google Chrome packages
  apt:
    update_cache: yes
    state: present
    name: google-chrome-stable
