---

- name: "apt | Add Google Chrome repository key"
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: "apt | Check if Google Chrome apt repository exists"
  stat:
    path: /etc/apt/sources.list.d/google-chrome.list
  register: gchrome_stat_result
  when: ansible_facts['os_family'] == "Debian"

- name: "apt | Configure Google Chrome repository"
  apt_repository:
    filename: google-chrome
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
  when: 
    - not gchrome_stat_result.stat.exists
    - /var/lib/snapd/snap

- name: "apt | Install Google Chrome package"
  apt:
    update_cache: yes
    state: present
    name: google-chrome-stable
  when: ansible_facts['os_family'] == "Debian"

- name: "dnf | Configure Google Chrome repository"
  copy:
    dest: /etc/yum.repos.d/google-chrome.repo
    owner: root
    group: root
    mode: '0644'
    content: |
      [google-chrome]
      name=google-chrome
      baseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64
      enabled=1
      gpgcheck=1
      gpgkey=http://dl-ssl.google.com/linux/linux_signing_key.pub
  when: ansible_facts['distribution'] == "Fedora"

- name: "rpm | Import Google Chrome repo key"
  rpm_key:
    state: present
    key: http://dl-ssl.google.com/linux/linux_signing_key.pub
  when: ansible_facts['distribution'] == "Fedora"

- name: "dnf | Install Google Chrome package"
  dnf:
    name: google-chrome-stable
    state: latest
  when: ansible_facts['distribution'] == "Fedora"
