---

- name: "dnf | Install snap daemon"
  dnf:
    name: snapd
    state: latest

- name: Add support for classic snaps
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    owner: root
    group: root
    state: link
  when: ansible_facts['distribution'] == "Fedora"
