---


- name: Install snap daemon
  apt:
    name: snapd

- name: Start and enable snapd daemon
  systemd:
    name: snapd
    state: started
    enabled: yes

- name: Install default snap packages
  snap:
    name:
      - cawbird
      - docker
      - telegram-desktop

- name: Install classic snap packages
  snap:
    name:
      - codium
      - kubectl
    classic: yes
