---

- include: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- include: fedora.yml
  when: ansible_facts['distribution'] == "Fedora"

- name: Start and enable snapd daemon
  service:
    name: snapd
    state: started
    enabled: yes

- name: Install default snap packages
  snap:
    name:
      - cawbird
      - discord
      - docker
      - mattermost-desktop
      - spotify
      - telegram-desktop

- name: Install classic snap packages
  snap:
    name:
      - codium
      - kubectl
    classic: yes
