---

- name: "apt | Add nextcloud repository key"
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1FCD77DD0DBEF5699AD2610160EE47FBAD3DD469

- name: "apt | Configure nextcloud repository"
  apt_repository:
    repo: deb http://ppa.launchpad.net/nextcloud-devs/client/ubuntu eoan main

- name: "apt | Install nextcloud packages"
  apt:
    update_cache: yes
    state: present
    pkg:
    - nextcloud-client
    - nextcloud-client-nautilus
