---

- name: Check if root's git config exists
  stat:
    path: /root/.gitconfig
  register: stat_gitconfig

- name: Basic git configuration for root user
  copy:
    dest: /root/.gitconfig
    owner: root
    group: root
    mode: '0640'
    content: |
      [user]
        name = root
        email = root@localhost
      [push]
        default = simple
  when: not stat_gitconfig.stat.exists

- include: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- include: fedora.yml
  when: ansible_facts['distribution'] == "Fedora"

- name: Configure etckeeper
  copy:
    src: etckeeper.conf
    dest: /etc/etckeeper/etckeeper.conf
    owner: root
    group: root
    mode: '0644'
