---

- name: "apt | Install git"
  apt:
    name: git
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: "dnf | Install git"
  dnf:
    name: git
    state: latest
  when: ansible_facts['distribution'] == "Fedora"

- name: Check if root's git config exists
  stat:
    path: /root/.gitconfig
  register: stat_gitconfig

- name: Basic git configuration for root user
  copy:
    dest: /root/.gitconfig
    owner: root
    group: root
    mode: '0640'
    content: |
      [user]
        name = root
        email = root@localhost
      [push]
        default = simple
  when: not stat_gitconfig.stat.exists

- name: "apt | Install etckeeper"
  apt:
    name: etckeeper
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: "dnf | Install etckeeper"
  dnf:
    name: etckeeper
    state: latest
  when: ansible_facts['distribution'] == "Fedora"

- name: Configure etckeeper
  copy:
    src: etckeeper.conf
    dest: /etc/etckeeper/etckeeper.conf
    owner: root
    group: root
    mode: '0644'
