---

- name: "dnf | Upgrade all dnf packages"
  dnf:
    name: "*"
    state: latest

- name: "dnf | Install base dnf packages"
  dnf:
    name:
      - htop
      - atop
      - iotop
      - direnv
      - borgbackup
      - ImageMagick
      - libreoffice-writer
      - libreoffice-calc
      - libreoffice-gtk3
      - pwgen
      - wireguard-tools
      - qemu
      - libvirt-daemon
      - virt-manager
      - tmux
      - vim
